[program:symphony-sshd]
command=/usr/local/bin/symphony-sshd-start
user=root
autorestart=true
stdout_logfile=/var/log/supervisor/symphony-sshd.log
stderr_logfile=/var/log/supervisor/symphony-sshd.error.log
priority=40
